// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922190357_AddAdminAndModeration")]
    partial class AddAdminAndModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BackendApi.Domain.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("BackendApi.Domain.AdminAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("AdminAuditEntries");
                });

            modelBuilder.Entity("BackendApi.Domain.CourseProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReviewedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("CourseProposals");
                });

            modelBuilder.Entity("BackendApi.Domain.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("BackendApi.Domain.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("LessonId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("BackendApi.Domain.GradeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GradingComponentId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradingComponentId");

                    b.ToTable("GradeEntries");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GradingSchemeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GradingSchemeId");

                    b.ToTable("GradingComponents");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("GradingSchemes");
                });

            modelBuilder.Entity("BackendApi.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ContentUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ForkSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForkedFromAuthorName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForkedFromLessonId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModerationLockReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ModerationLockedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SharedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("BackendApi.Domain.LessonLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "UserId")
                        .IsUnique();

                    b.ToTable("LessonLikes");
                });

            modelBuilder.Entity("BackendApi.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("BackendApi.Domain.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlashcardIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("QuizSessions");
                });

            modelBuilder.Entity("BackendApi.Domain.ShareBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hours")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IssuedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LiftedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LiftedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartsAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("ShareBans");
                });

            modelBuilder.Entity("BackendApi.Domain.ShareEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("ShareEvents");
                });

            modelBuilder.Entity("BackendApi.Domain.SpacedRepetitionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Due")
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lapses")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearningStepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("NextReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId")
                        .IsUnique();

                    b.ToTable("SpacedRepetitionStates");
                });

            modelBuilder.Entity("BackendApi.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyllabusFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyllabusRawText")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniversityCourseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniversityCourseId");

                    b.HasIndex("UserId", "UniversityCourseId")
                        .IsUnique()
                        .HasFilter("\"UniversityCourseId\" IS NOT NULL");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BackendApi.Domain.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("BackendApi.Domain.UniversityCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityCourses");
                });

            modelBuilder.Entity("BackendApi.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniversityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UniversityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApi.Domain.UserSrsSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DailySessionSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayRolloverHour")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EasyBonus")
                        .HasColumnType("REAL");

                    b.Property<int>("EasyIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduatingIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HardMultiplier")
                        .HasColumnType("REAL");

                    b.Property<double>("LapseNewIntervalMultiplier")
                        .HasColumnType("REAL");

                    b.Property<string>("LearningStepsMinutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewCardsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelearningStepsMinutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StartingEase")
                        .HasColumnType("REAL");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSrsSettings");
                });

            modelBuilder.Entity("BackendApi.Domain.Admin", b =>
                {
                    b.HasOne("BackendApi.Domain.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("University");
                });

            modelBuilder.Entity("BackendApi.Domain.CourseProposal", b =>
                {
                    b.HasOne("BackendApi.Domain.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApi.Domain.Deck", b =>
                {
                    b.HasOne("BackendApi.Domain.Lesson", "Lesson")
                        .WithMany("Decks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BackendApi.Domain.Flashcard", b =>
                {
                    b.HasOne("BackendApi.Domain.Deck", "Deck")
                        .WithMany("Flashcards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BackendApi.Domain.Lesson", "Lesson")
                        .WithMany("Flashcards")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BackendApi.Domain.GradeEntry", b =>
                {
                    b.HasOne("BackendApi.Domain.GradingComponent", "GradingComponent")
                        .WithMany("Entries")
                        .HasForeignKey("GradingComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingComponent");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingComponent", b =>
                {
                    b.HasOne("BackendApi.Domain.GradingScheme", "GradingScheme")
                        .WithMany("Components")
                        .HasForeignKey("GradingSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingScheme");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingScheme", b =>
                {
                    b.HasOne("BackendApi.Domain.Subject", "Subject")
                        .WithOne("GradingScheme")
                        .HasForeignKey("BackendApi.Domain.GradingScheme", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApi.Domain.Lesson", b =>
                {
                    b.HasOne("BackendApi.Domain.Subject", "Subject")
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApi.Domain.LessonLike", b =>
                {
                    b.HasOne("BackendApi.Domain.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BackendApi.Domain.Note", b =>
                {
                    b.HasOne("BackendApi.Domain.Lesson", "Lesson")
                        .WithMany("Notes")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BackendApi.Domain.QuizSession", b =>
                {
                    b.HasOne("BackendApi.Domain.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BackendApi.Domain.SpacedRepetitionState", b =>
                {
                    b.HasOne("BackendApi.Domain.Flashcard", "Flashcard")
                        .WithOne("ReviewState")
                        .HasForeignKey("BackendApi.Domain.SpacedRepetitionState", "FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("BackendApi.Domain.Subject", b =>
                {
                    b.HasOne("BackendApi.Domain.UniversityCourse", "UniversityCourse")
                        .WithMany()
                        .HasForeignKey("UniversityCourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UniversityCourse");
                });

            modelBuilder.Entity("BackendApi.Domain.UniversityCourse", b =>
                {
                    b.HasOne("BackendApi.Domain.University", "University")
                        .WithMany("Courses")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("BackendApi.Domain.User", b =>
                {
                    b.HasOne("BackendApi.Domain.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("University");
                });

            modelBuilder.Entity("BackendApi.Domain.Deck", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("BackendApi.Domain.Flashcard", b =>
                {
                    b.Navigation("ReviewState");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingComponent", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BackendApi.Domain.GradingScheme", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("BackendApi.Domain.Lesson", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Flashcards");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("BackendApi.Domain.Subject", b =>
                {
                    b.Navigation("GradingScheme");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("BackendApi.Domain.University", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
